{% set name = "slack_sdk" %}
{% set version = "3.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slack_sdk-{{ version }}.tar.gz
  sha256: 195f044e02a2844579a7a26818ce323e85dde8de224730c859644918d793399e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - slack_sdk
    - slack_sdk.web
    - slack_sdk.webhook
    - slack_sdk.signature
    - slack_sdk.socket_mode
    - slack_sdk.audit_logs
    - slack_sdk.scim
    - slack_sdk.oauth
    - slack_sdk.models
  commands:
    - pip check
    - conda install -y aiohttp
    - python -c "import slack_sdk.rtm"
  requires:
    - pip

about:
  home: https://github.com/slackapi/python-slack-sdk
  summary: The Slack API Platform SDK for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
